// Generated by: Claude Sonnet 4.6
// Model version: claude-sonnet-4-20250514
// Prompt: MAC module spec (synchronous active-high reset, signed 8-bit inputs, 32-bit accumulator)

module mac (
    input  logic        clk,
    input  logic        rst,
    input  logic signed [7:0]  a,
    input  logic signed [7:0]  b,
    output logic signed [31:0] out
);

    logic signed [15:0] product;

    always_ff @(posedge clk) begin
        if (rst) begin
            out <= 32'sd0;
        end else begin
            product <= a * b;
            out <= out + product;
        end
    end

endmodule
