// Generated by: GPT-4o
// Model version: gpt-4o-2024-08-06
// Prompt: MAC module spec (synchronous active-high reset, signed 8-bit inputs, 32-bit accumulator)

module mac (
    input  wire        clk,
    input  wire        rst,
    input  wire signed [7:0]  a,
    input  wire signed [7:0]  b,
    output reg  signed [31:0] out
);

    // Active-low reset: clear accumulator when rst is deasserted
    always @(posedge clk) begin
        if (!rst) begin
            out <= 32'd0;
        end else begin
            out <= out + (a * b);
        end
    end

endmodule
